<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ttxt</string>
	</array>
	<key>name</key>
	<string>Plain Text (Tanuki)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>&lt;%#</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.erb</string>
				</dict>
			</dict>
			<key>end</key>
			<string>%&gt;</string>
			<key>name</key>
			<string>comment.block.erb</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*%%|&lt;%%</string>
			<key>name</key>
			<string>text.plain</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;%[=!?_]?</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.ruby</string>
				</dict>
			</dict>
			<key>end</key>
			<string>-?%&gt;</string>
			<key>name</key>
			<string>source.ruby.tanuki.embedded.text</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>%%&gt;</string>
					<key>name</key>
					<string>punctuation.section.embedded.ruby</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.ruby</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(#).*?(?=-?%&gt;)</string>
					<key>name</key>
					<string>comment.line.number-sign.ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.ruby</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*%</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>source.ruby.tanuki.embedded.text</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>%%&gt;</string>
					<key>name</key>
					<string>punctuation.section.embedded.ruby</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.ruby</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(#).*?(?=-?%&gt;)</string>
					<key>name</key>
					<string>comment.line.number-sign.ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.ruby</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.tanuki</string>
	<key>uuid</key>
	<string>2C70B745-C5B1-4EEB-BF91-2D62E1880C7D</string>
</dict>
</plist>
